-- noinspection SqlNoDataSourceInspectionForFile

# --- !Ups

CREATE TABLE "events"
(
  "id"   bigint generated by default as identity (start with 1) not null primary key,
  "name" varchar not null
);

# --- !Downs
DROP TABLE "events";